# Using Numpy library

In [3]:
import numpy as np
import math

In [7]:
#We can create list of arrays using np.array and list of lists which is a multidimensional array

a = np.array([1,2,3])
print(a)
#print the number of dimensions
print(a.ndim)

b = np.array([[1,2,3],[4,5,6]])
print(b)

#we can print out the length of each dimensions by calling shape attribute, returning a tuple
b.shape

[1 2 3]
1
[[1 2 3]
 [4 5 6]]


(2, 3)